# Generated by Django 3.1 on 2020-09-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymousman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.SlugField(blank=True, max_length=16, null=True, unique=True)),
                ('ip', models.CharField(editable=False, max_length=16)),
                ('dating', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
